image: gradle:5.0.0-jdk8

stages:
  - build
  - test

gradle-build:
  stage: build
  script: "./gradlew build -x test"
  artifacts:
    paths:
      - build/libs/*.jar

gradle-test:
  stage: test
  script: "./gradlew build -q test"