image: docker:latest
services:
  - docker:dind

stages:
  - build
  - package

gradle-build:
  image: gradle:5.0.0-jdk8
  stage: build
  script: "gradle build"
  artifacts:
    paths:
      - build/libs/*.jar

docker-build:
  stage: package
  script:
    - docker build -t jdube/simplenotes:$CI_COMMIT_SHORT_SHA .
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - docker push jdube/simplenotes:$CI_COMMIT_SHORT_SHA